version: 2

models:
  - name: stg_fred_indicators
    description: "Staging model for FRED economic indicators - cleaned and standardized"
    columns:
      - name: indicator_id
        description: "Unique identifier for the economic indicator"
        tests:
          - not_null
      - name: observation_date
        description: "Date of the observation"
        tests:
          - not_null
      - name: value
        description: "Indicator value"
        tests:
          - not_null

  - name: int_macro_signals
    description: "Intermediate model with calculated macro signals and trend analysis"
    columns:
      - name: indicator_id
        tests:
          - not_null
      - name: month
        tests:
          - not_null

  - name: fct_regime_inputs
    description: "Gold layer fact table with aggregated risk scores by month"
    columns:
      - name: month
        description: "Month of observation"
        tests:
          - not_null
          - unique
      - name: avg_risk_score
        description: "Average risk score across all indicators (-2 to +1 scale)"

  - name: decision_monthly_regime
    description: "Final monthly regime decision: RISK_ON, NEUTRAL, or RISK_OFF"
    columns:
      - name: month
        tests:
          - not_null
          - unique
      - name: regime
        description: "Regime classification"
        tests:
          - not_null
          - accepted_values:
              values: ['RISK_ON', 'NEUTRAL', 'RISK_OFF']
      - name: confidence
        tests:
          - accepted_values:
              values: ['HIGH', 'MEDIUM', 'LOW']